######################## SETUP application.properties ########################

## General setup
server.port = 8080
vaadin.launch-browser = true

## Terminal setup - text color, formating, disable logging... 
spring.output.ansi.enabled = always  
logging.pattern.console = %cyan(%d{HH:mm:ss}) [%green(%level)]  %cyan(%msg%n)
logging.level.root = WARN

## Files Uploading setup
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 16GB
spring.servlet.multipart.max-request-size = 16GB

## MongoDB setup connection
spring.data.mongodb.uri = mongodb+srv://reuveni:216224188@cluster0.n5662fu.mongodb.net/DemoDB

## cookies settings
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=30m

#############################################################################